### ISSUE TITLE
packet error on minimal minestom server

### ISSUE THREAD

**Issue by Sombian** [OneLiteFeatherNET/Microtus#47]
the issue seems to persist when a player interacts with an (any) itemstack in invenory.
e.g. moving the item
thus i feel very confident this has to do with `SetSlotPacket`.

```java
	public static void main(final String[] args) {
		//
		// create a server
		//
		final var server = MinecraftServer.init(); MojangAuth.init();
		//
		// minestom by default generates random UUID each time player connects
		// whilst the generated uuid is indeed unique, it is not persistent, and i don't want that
		//
		MinecraftServer.getConnectionManager().setUuidProvider((connection, username) -> {
			//
			// make a request to mojang api
			//
			final var id = MojangUtils.fromUsername(username).get("id").getAsString();

			return UUID.fromString(String.format("%s-%s-%s-%s", id.substring(0, 7), id.substring(7, 11), id.substring(11, 15), id.substring(15, 20)));
		});
		//
		// configure player spawn
		//
		MinecraftServer.getGlobalEventHandler().addListener(PlayerLoginEvent.class, (event) -> {
			event.setSpawningInstance(/* YOUR WORLD */);
			event.getPlayer().setRespawnPoint(new Pos(0, 1, 0));
			event.getPlayer().getInventory().addItemStack(ItemStack.of(Material.ICE)); // <-- HERE

		});
		//
		// start the server
		//
		server.start("0.0.0.0", 25565);
	}
```

```bash
[Ms-worker-2] [06:53:20] (PlayerSocketConnection.lambda$processPackets$0) - WARN - WARNING: Packet 0x20 not fully read (java.nio.DirectByteBuffer[pos=1 lim=5 cap=5]) null
java.lang.IndexOutOfBoundsException
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:751)
	at java.base/java.nio.DirectByteBuffer.getLong(DirectByteBuffer.java:801)
	at net.minestom.server.network.NetworkBufferTypes.lambda$static$11(NetworkBufferTypes.java:92)
	at net.minestom.server.network.NetworkBuffer.read(NetworkBuffer.java:119)
	at net.minestom.server.network.NetworkBufferTypes.lambda$static$31(NetworkBufferTypes.java:303)
	at net.minestom.server.network.NetworkBuffer.read(NetworkBuffer.java:119)
	at net.minestom.server.crypto.ChatSession.<init>(ChatSession.java:10)
	at net.minestom.server.network.packet.client.play.ClientChatSessionUpdatePacket.<init>(ClientChatSessionUpdatePacket.java:10)
	at net.minestom.server.network.packet.client.ClientPacketsHandler.create(ClientPacketsHandler.java:35)
	at net.minestom.server.network.PacketProcessor.create(PacketProcessor.java:32)
	at net.minestom.server.network.PacketProcessor.process(PacketProcessor.java:45)
	at net.minestom.server.network.player.PlayerSocketConnection.lambda$processPackets$0(PlayerSocketConnection.java:109)
	at net.minestom.server.utils.PacketUtils.readPackets(PacketUtils.java:230)
	at net.minestom.server.network.player.PlayerSocketConnection.processPackets(PlayerSocketConnection.java:103)
	at net.minestom.server.network.socket.Worker.lambda$run$0(Worker.java:79)
	at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:297)
	at java.base/sun.nio.ch.WEPollSelectorImpl.processEvents(WEPollSelectorImpl.java:186)
	at java.base/sun.nio.ch.WEPollSelectorImpl.doSelect(WEPollSelectorImpl.java:122)
	at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130)
	at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:162)
	at net.minestom.server.network.socket.Worker.run(Worker.java:59)
```

**Comment by theEvilReaper** [comment]
Hey @Sombian, thanks for reporting the issues. Can you tell me which version of `Microtus` you are using for this project?

**Comment by Sombian** [comment]
@theEvilReaper 

```gradle
repositories {
	mavenCentral()
	maven("https://jitpack.io")
	maven("https://oss.sonatype.org/content/repositories/snapshots")
}

dependencies {
	implementation("net.onelitefeather.microtus:Minestom:1.1.1-SNAPSHOT+a8e43bb")
}

configurations.all {
	resolutionStrategy {
		force("com.google.code.gson:gson:2.10.1")
	}
}
```

**Comment by Sombian** [comment]
@theEvilReaper indeed, the issue is resolved in latest release, my apologies.
